# Generated by Django 5.1 on 2024-09-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
