# Generated by Django 5.1 on 2024-09-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note_alter_note_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table=None,
        ),
    ]
